# Generated by Django 2.2.1 on 2019-08-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='description')),
                ('state', models.IntegerField(choices=[(1, 'to do'), (2, 'done')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
