# Generated by Django 2.2.1 on 2019-08-12 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Task', '0002_usertasks_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertasks',
            name='first_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='first_e', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
