# Generated by Django 2.2.1 on 2019-08-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_usertasks_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertasks',
            name='first_name',
        ),
    ]
